[workspace]
resolver = "2"
members = ["bench-rocksdb", "bench-pg"]

[workspace.package]
authors = ["mingyang91 <my@famer.me>"]
edition = "2024"
license = "MIT"
rust-version = "1.80"

[workspace.dependencies]
openmatching = { path = "openmatching", version = "0.1.0" }
