name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: openmatching
            asset_name: openmatching-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: openmatching
            asset_name: openmatching-darwin-amd64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.x"
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
